input:
  path: "./data/input/[AD39] JUI-EST-INST-RS-001 Is2.2_JUICE Instruments Reduced Thermal Model Specification.pdf"
  mode: "pdf"
  recursive: false

output:
  directory: "./data/output"

pdf:
  markdown_output_dir: "./data/markdown_output"

chunking:
  strip_headers: false

extraction:
  model_name: "llama3:latest"

parallel:
  enabled: true
  max_workers: 5

ollama:
  host: "http://localhost:11434"
  timeout_seconds: 1800

logging:
  level: "DEBUG"
